### ISSUE TITLE
Your data is either not formatted correctly or outdated.

### ISSUE THREAD

**Issue by Pickles726** [desophos/idleon-saver#13]
**Problem**
Attempting to import idleon_save.json fails on Idleon Companion with an error stating that your data is not formatted correctly or outdated. Clicking on export to idleon companion within IdleonSaver also errors out.

**To Reproduce**
1. Open Idleon.
2. Select a character and collect afk gains.
3. Switch character and go to character screen.
4. Exit.
5. Run Idleon Saver. 
6. Specify Location of Idleon.
7. idleon_save.json is created.
8. Press Export to receive error.

**Expected behavior**
Import into Idleon Companion with idleon_save.json or exported through the button selection within IdleonSaver

**Log file**
[log_21-11-01_1.txt](https://github.com/desophos/idleon-saver/files/7451272/log_21-11-01_1.txt)
[log_21-11-01_0.txt](https://github.com/desophos/idleon-saver/files/7451273/log_21-11-01_0.txt)

**Screenshots**
![firefox_2021-11-01_01-08-43](https://user-images.githubusercontent.com/30604149/139634981-05583ef2-4395-4320-81e9-3a1a0423450b.png)
![IdleonSaver_2021-11-01_01-12-26](https://user-images.githubusercontent.com/30604149/139635012-ecb5d975-7523-4c84-a597-9afad30ad2ac.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Seems like there may be something within the acquired data that is causing the NoneType stack. Please see attached idleon_save.zip
[idleon_save.zip](https://github.com/desophos/idleon-saver/files/7451291/idleon_save.zip)

**Comment by desophos** [comment]
Thank you for attaching your save data! You were right, there was an unexpected null field that caused the error. This should be fixed in the newest build: https://github.com/desophos/idleon-saver/suites/4224242165/artifacts/109269256

**Comment by Pickles726** [comment]
Thanks for the fix! You're doing excellent work. :)
