### ISSUE TITLE
 'Cannot find context with specified id'

### ISSUE THREAD

**Issue by gewaltgamer** [desophos/idleon-saver#14]
**Describe the problem**
When launching game, Idleon saver briefly flashes a transparent window ( looks like same dimensions as game), then that closes and Idleon Saver goes to error screen.  please upload logs

**To Reproduce**
3. See logs

**Expected behavior**

**Log file**
[logs.zip](https://github.com/desophos/idleon-saver/files/7456965/logs.zip)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10, 21H2

**Additional context**
steamlibrary is not on C:\, had to manually enter game file location, it was verified via cmd

**Comment by gewaltgamer** [comment]
dunno how to upload files here sorry

`[INFO   ] Logger: Record log in C:\Users\Mike\AppData\Roaming\IdleonSaver\logs\log_21-11-01_8.txt
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "C:\Users\Mike\AppData\Local\Temp\_MEI156082\kivy\__init__.pyc"
[INFO   ] Python: v3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
[INFO   ] Python: Interpreter at "C:\Users\Mike\Desktop\IdleonSaver.exe"
[INFO   ] Factory: 186 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <b'4.6.0 NVIDIA 466.77'>
[INFO   ] GL: OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] GL: OpenGL renderer <b'NVIDIA GeForce GTX 750 Ti/PCIe/SSE2'>
[INFO   ] GL: OpenGL parsed version: 4, 6
[INFO   ] GL: Shading version <b'4.60 NVIDIA'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <32>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] GL: NPOT texture support is available
[INFO   ] Base: Start application main loop
[INFO   ] Clipboard: Provider: winctypes
[INFO   ] Launching binary "E:\SteamLibrary\steamapps\common\Legends of Idleon\LegendsOfIdleon.exe"
[INFO   ] Setting up websocket connection for key '0303c930-f741-4e98-aa19-6a1256fbd586'
[INFO   ] Entering chrome context
[ERROR  ] Exception in chrome context!
[ERROR  ] Traceback (most recent call last):
[ERROR  ]   File "ChromeController\chrome_context.py", line 23, in ChromeContext
[ERROR  ]   File "idleon_saver\scripts\inject.py", line 31, in main
[ERROR  ]   File "ChromeController\manager.py", line 685, in execute_javascript_statement
[ERROR  ]   File "ChromeController\manager.py", line 433, in __exec_js
[ERROR  ]   File "ChromeController\manager.py", line 374, in __unwrap_object_return
[ERROR  ]   File "ChromeController\Generator\Generated.py", line 11937, in Runtime_getProperties
[ERROR  ]   File "ChromeController\manager_base.py", line 128, in synchronous_command
[ERROR  ]   File "ChromeController\manager_base.py", line 106, in __check_ret
[ERROR  ] ChromeController.cr_exceptions.ChromeError: Error in response: 
[ERROR  ] {'error': {'code': -32000, 'message': 'Cannot find context with specified id'},
[ERROR  ]  'id': 2}
[ERROR  ] 
[INFO   ] Exiting chrome context
[INFO   ] Closing all tabs.
[INFO   ] Closing tab 0303c930-f741-4e98-aa19-6a1256fbd586 (cr ID: 8C561737A8A1A65F1885EDE5030E324A)
[INFO   ] Closing websocket connecton 0303c930-f741-4e98-aa19-6a1256fbd586 (1)
[INFO   ] All tabs are closed. Closing chromium!
[INFO   ] Websocket Teardown called
[ERROR  ] Error in response: 
{'error': {'code': -32000, 'message': 'Cannot find context with specified id'},
 'id': 2}
Traceback (most recent call last):
  File "main.py", line 211, in resolve_action
    self.action(path)
  File "main.py", line 269, in get_json
    rawdata = self.get_stencyl(path)
  File "main.py", line 266, in get_stencyl
    return inject.main(Path(path))
  File "idleon_saver\scripts\inject.py", line 31, in main
  File "ChromeController\manager.py", line 685, in execute_javascript_statement
  File "ChromeController\manager.py", line 433, in __exec_js
  File "ChromeController\manager.py", line 374, in __unwrap_object_return
  File "ChromeController\Generator\Generated.py", line 11937, in Runtime_getProperties
  File "ChromeController\manager_base.py", line 128, in synchronous_command
  File "ChromeController\manager_base.py", line 106, in __check_ret
ChromeController.cr_exceptions.ChromeError: Error in response: 
{'error': {'code': -32000, 'message': 'Cannot find context with specified id'},
 'id': 2}
`

**Comment by gewaltgamer** [comment]
[logs.zip](https://github.com/desophos/idleon-saver/files/7456963/logs.zip)
Figured it out!

**Comment by desophos** [comment]
I honestly have no idea why this error happens, but I'm investigating alternate methods of obtaining the data that would bypass this problem entirely. It doesn't seem to be related to Idleon being on a different drive, since #22 has Idleon on the C drive.

**Comment by desophos** [comment]
Please try [version 3.0.0](https://github.com/desophos/idleon-saver/releases/tag/v3.0.0), which should fix this issue.

**Comment by desophos** [comment]
Closing as fixed; please reopen if this error still occurs.
