### ISSUE TITLE
Failed exporting to IdleonCompanion

### ISSUE THREAD

**Issue by ryancflowers** [desophos/idleon-saver#15]
**Describe the problem**
Fails to export save for idleoncompanion

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Export save like normal
2. Click "export to idleoncompanion" button
3. Error appears consistently

**Expected behavior**
export file to be created

**Log file**
Please attach your log file, found at `%APPDATA%\IdleonSaver\idleon_saver.log`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Works fine on my desktop, but this issue appears when grabbing the save from my laptop
[logs.zip](https://github.com/desophos/idleon-saver/files/7529762/logs.zip)
[idleon_save.zip](https://github.com/desophos/idleon-saver/files/7529773/idleon_save.zip)

**Comment by desophos** [comment]
Please try again with [the new version](https://github.com/desophos/idleon-saver/releases/tag/v2.0.2) and reopen this issue if you still encounter this problem.
