### ISSUE TITLE
Couldn't export to Idleon Companion

### ISSUE THREAD

**Issue by Zelge** [desophos/idleon-saver#16]
**Describe the problem**

**To Reproduce**
Steps to reproduce the behavior, for example:
3. See error

**Expected behavior**

**Log file**
Please attach your log file, found at `%APPDATA%\IdleonSaver\idleon_saver.log`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by Zelge** [comment]
[logs.zip](https://github.com/desophos/idleon-saver/files/7631904/logs.zip)
doesnt allow the json file to be uploaded here

**Comment by desophos** [comment]
Please try again with [the new version](https://github.com/desophos/idleon-saver/releases/tag/v2.0.2) and reopen this issue if you still encounter this problem.
