### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by Krysommor** [desophos/idleon-saver#17]
**Describe the problem**

**To Reproduce**
save Json
Try to upload to idleoncompanion.com
does not like the format

**Expected behavior**

**Log file**
Please attach your log file, found at `%APPDATA%\IdleonSaver\idleon_saver.log`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Add any other context about the problem here
[log_21-12-07_0.txt](https://github.com/desophos/idleon-saver/files/7672292/log_21-12-07_0.txt)
.

**Comment by desophos** [comment]
Please try again with [the new version](https://github.com/desophos/idleon-saver/releases/tag/v2.0.2) and reopen this issue if you still encounter this problem.
