### ISSUE TITLE
idleonsaver not working

### ISSUE THREAD

**Issue by kennykeg89** [desophos/idleon-saver#18]
**Describe the problem**
keeps saying it is not formatted correctly or out of date

**To Reproduce**
Steps to reproduce the behavior, for example:
1. ran program
2. selected export to idleon companion
3. See error
4. tried pasting it manually
5. see error

**Desktop (please complete the following information):**
 - OS: [Windows 10]

log file
[logs.zip](https://github.com/desophos/idleon-saver/files/7688049/logs.zip)

i have tried opening it and closing it multiple times. i collected all my items with each character. tried changing presets, collecting cogs, leveling bubbles and nothing seems to help.

**Comment by desophos** [comment]
Please try again with [the new version](https://github.com/desophos/idleon-saver/releases/tag/v2.0.2) and reopen this issue if you still encounter this problem.
