### ISSUE TITLE
Second save bugged

### ISSUE THREAD

**Issue by Dexter3x1** [desophos/idleon-saver#23]
**Describe the problem**
I already used this tool and it wen well. The second time I used it gave me this error when i wanted to convert my data to IdleonCompanion format

**To Reproduce**
First ) Simply Extracting 
Second ) Click on "Export to Idleon Companion

**Expected behavior**
Having the file converted succesfully in the right format
**Log file**
Please attach your log file, found at `%APPDATA%\IdleonSaver\idleon_saver.log`.
[logs.zip](https://github.com/desophos/idleon-saver/files/7711871/logs.zip)
**Screenshots**

[image](https://user-images.githubusercontent.com/13915134/146006431-ef09dc9c-67f6-4ee0-8570-05a227b35671.png)
The screen before the error
**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
![image](https://user-images.githubusercontent.com/13915134/146006431-ef09dc9c-67f6-4ee0-8570-05a227b35671.png)

**Comment by Dexter3x1** [comment]
Oh okay, so i just have to stay tuned for any update of the idleonsaver then. Thanks :)

**Comment by rasmusgu** [comment]
No problem, but I'd personally leave the issue up since it hasn't been fixed and we want the maintainer(s) to see it in hopes of an update. Though there are numerous duplicative reports on the same issue, yours is the most recent and more informative than many, doubly so with my added contribution.

**Comment by desophos** [comment]
All KeyErrors should be fixed in [version 2.0.3](https://github.com/desophos/idleon-saver/releases/tag/v2.0.3). v2.0.2 didn't contain data for the new Giftmas card, which has been added in v2.0.3.
