### ISSUE TITLE
Cannot convert exported data to idleon companion format

### ISSUE THREAD

**Issue by nolkel** [desophos/idleon-saver#24]
**Describe the problem**
After reading the data from the Steam version of the game, I tried to export it to Idleon Companion format. I get an error "Oops! Something went wrong."

**Log file**
Please attach your log file, found at `%APPDATA%\IdleonSaver\idleon_saver.log`.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
[logs.zip](https://github.com/desophos/idleon-saver/files/7713624/logs.zip)

**Comment by desophos** [comment]
Please try again with [the new version](https://github.com/desophos/idleon-saver/releases/tag/v2.0.2) and reopen this issue if you still encounter this problem.

**Comment by nolkel** [comment]
I have the same issue with the 2.0.2 release. Attached logs.

[logs.zip](https://github.com/desophos/idleon-saver/files/7716861/logs.zip)

**Comment by Sno-sno** [comment]
[logs.zip](https://github.com/desophos/idleon-saver/files/7721256/logs.zip)
Same Issue, 2.0.2

**Comment by desophos** [comment]
These errors should be fixed in [version 2.0.3](https://github.com/desophos/idleon-saver/releases/tag/v2.0.3).
