### ISSUE TITLE
Null return value from Runtime.evaluate

### ISSUE THREAD

**Issue by 2zef** [desophos/idleon-saver#25]
[**Describe] the problem**
When I launch the application I follow the small tutorial and I simply specify the path of LegendsOfIdleon.exe.
 I click on next, a bar appears and the game tries to launch, without any effect, It is at this moment that the error word appears.

**To Reproduce**
Just follow the tutorial and the error message that appears.

**Log file**
[log_21-12-15_2.txt](https://github.com/desophos/idleon-saver/files/7719213/log_21-12-15_2.txt)

**Screenshots**
![Sans titre](https://user-images.githubusercontent.com/96182826/146184960-5553e992-0ab1-4017-b409-adef004a6bcd.png)

**Desktop (please complete the following information):**
 - OS Windows 10 21H1

**Comment by desophos** [comment]
Did you try logging into a character in-game, then closing the game and running Idleon Saver again?

**Comment by desophos** [comment]
Please try [version 3.0.0](https://github.com/desophos/idleon-saver/releases/tag/v3.0.0), which should fix this issue.

**Comment by 2zef** [comment]
Yes, it works! Well done and thanks for the help.
Sorry for not replying I didn't get the notification !
Happy new year :)

**Comment by desophos** [comment]
Happy new year! Fixed in v3.0.0
