### ISSUE TITLE
Missing alchemy/construction data causes errors in export

### ISSUE THREAD

**Issue by Maesterrr** [desophos/idleon-saver#26]
Went through the steps to create file but get this error when i try and import and get another error by manually trying to import the file saying the version or format may be wrong

![image](https://user-images.githubusercontent.com/96203525/146249734-8189c2fa-5bb3-457e-815f-0725273e9af5.png)

[log_21-12-15_7.txt](https://github.com/desophos/idleon-saver/files/7722061/log_21-12-15_7.txt)

**Comment by desophos** [comment]
Hi, thanks for the report! Have you unlocked alchemy and construction in-game? And could you attach your `idleon_save.json` please? It should be in `C:\Users\<YOUR USERNAME>\AppData\Roaming\IdleonSaver`.

**Comment by Maesterrr** [comment]
Hey,

Yes I have, probably something silly I'm doing wrong but thanks for the
reply!

**Comment by Maesterrr** [comment]
I attached the file on the reply on gmail doesnt seem to allow me to post it on comments here

**Comment by desophos** [comment]
Hmm, can you add the file to the original post? It doesn't seem like the email attachment came through.

**Comment by desophos** [comment]
Ah right, I forgot GitHub doesn't like JSON files. Can you right click the file -> Send to -> Compressed (zipped) folder and upload the .zip file here?

**Comment by Maesterrr** [comment]
[idleon_save.zip](https://github.com/desophos/idleon-saver/files/7731149/idleon_save.zip)


Done!

**Comment by desophos** [comment]
Thanks, it looks like your local save data is extremely old. Have you ever run Legends of Idleon from a drive other than `D:`? And could you screenshot the path and contents of this directory please:
```
D:\Program Files (x86)\Steam\steamapps\common\Legends of Idleon\resources
```

**Comment by Maesterrr** [comment]
That's strange, no i don't think so and steam takes me to that folder when i ask for the file source, ill have a dig around and see is their files anywhere else
![Capture](https://user-images.githubusercontent.com/96203525/146624887-346815d8-d01f-423f-b386-2b041075344d.JPG)
e

**Comment by desophos** [comment]
Hmmm... I have a couple more ideas:
1. Do you know if your Legends of Idleon path has ever changed? For example, if you moved your Steam installation.
2. Usually this kind of thing happens because there are multiple keys in the localstorage database. Could you make a .zip of this `leveldb` folder and upload it here please? (You can press `⊞ Win` + `R` and paste this path there to open it.)
```
%APPDATA%\legends-of-idleon\Local Storage\leveldb
```

**Comment by Maesterrr** [comment]
I might have a while back, cant say for sure if i did with idleon but i have moved steam games around hardrives

[leveldb.zip](https://github.com/desophos/idleon-saver/files/7741864/leveldb.zip)

**Comment by desophos** [comment]
Thanks, that answered some questions. The only entry in there is for Legends of Idleon on your C: drive, which could be the root cause of all this. I'm more confused that there isn't a D: drive entry. Try deleting that `%APPDATA%\legends-of-idleon\Local Storage\leveldb` folder and running Idleon again. Warning: this might log you out and delete your presets (this is a bug in Idleon), so if you don't want to risk that then I understand.

**Comment by Maesterrr** [comment]
Still getting the same error after deleting the file, uninstalled and did a fresh install of the game on the D: drive too. This is the new zip file
[leveldb.zip](https://github.com/desophos/idleon-saver/files/7756828/leveldb.zip)

**Comment by desophos** [comment]
Well, that seems to have worked -- the leveldb data looks up to date now. Could you upload a .zip of the new logs please?

**Comment by Maesterrr** [comment]
[log_21-12-23_0.zip](https://github.com/desophos/idleon-saver/files/7766161/log_21-12-23_0.zip)

**Comment by desophos** [comment]
Oh, I see -- you're getting the `xmasEvent3` card error. Could you try [v2.0.3](https://github.com/desophos/idleon-saver/releases/download/v2.0.3/IdleonSaver.exe) please? That should fix this issue.

**Comment by Maesterrr** [comment]
still seem to be getting an error, logs for using the 2.0.3 version
think the log still says its 2.0.0 though i could be misreading, tried downloading it twice to be sure.


[log_21-12-28_4.zip](https://github.com/desophos/idleon-saver/files/7782603/log_21-12-28_4.zip)

**Comment by desophos** [comment]
That's really weird. Your alchemy data was present in the previous log, but empty in this log. I'm not sure why this would happen. Could you run Idleon, play a character, close Idleon, run Idleon Saver, and then attach your new leveldb please?

**Comment by desophos** [comment]
Please try [version 3.0.0](https://github.com/desophos/idleon-saver/releases/tag/v3.0.0), which should fix this issue.
