### ISSUE TITLE
KeyError on `xmasEvent3` card

### ISSUE THREAD

**Issue by MenacingSociety** [desophos/idleon-saver#27]
![image_2021-12-15_234214](https://user-images.githubusercontent.com/96212081/146281911-ff4606f9-658d-4298-9395-4833fe97c1a6.png)

[logs.zip](https://github.com/desophos/idleon-saver/files/7723506/logs.zip)

**Comment by desophos** [comment]
Thanks for the report, this should be a quick fix.

**Comment by desophos** [comment]
This should be fixed in [version 2.0.3](https://github.com/desophos/idleon-saver/releases/tag/v2.0.3). Please try it and reopen this issue if you encounter this problem again.
