### ISSUE TITLE
Export fails on characters that have never been logged in to

### ISSUE THREAD

**Issue by Epitask** [desophos/idleon-saver#28]
Exporting the json file to idleon companion, by clicking the export button in idleon saver, or uploading it on the idleon companion website do not work. Idleon saver simply says an error occurred, and idleon companion says it is either outdated or formatted incorrectly. Trying any of the suggested fixes on IdleonSaver's github page do not work. I am using the latest version on windows 10.

**Log file**
[log_21-12-20_5.txt](https://github.com/desophos/idleon-saver/files/7746842/log_21-12-20_5.txt)

**Comment by desophos** [comment]
Interesting, it seems like one of your characters might have an empty StatList for some reason. Could you make a .zip file with your `idleon_save.json` and upload it here please? It should be in `C:\Users\<YOUR USERNAME>\AppData\Roaming\IdleonSaver`.

**Comment by Epitask** [comment]
Here's the json in a .zip file. I apologize for the wait.
[idleon_save.zip](https://github.com/desophos/idleon-saver/files/7756335/idleon_save.zip)

**Comment by desophos** [comment]
Thanks, I see what the problem is: your character Cowboy_Bebob has a placeholder StatList with 4 zeroes. IDK why it doesn't include a fifth zero as a placeholder level -- blame Lava. Have you ever logged in to Cowboy_Bebob?

**Comment by Epitask** [comment]
I thought that I did log in to that character, though I haven't done a single thing with them besides log in to them, I believe.

**Comment by desophos** [comment]
Idleon Saver needs to handle this case, but try doing some stuff with them and see if that fixes the issue.
