### ISSUE TITLE
Export fails on empty StarSign

### ISSUE THREAD

**Issue by mindofender** [desophos/idleon-saver#29]
I'm continously getting the "Oops!  Something went wrong" error, and it told me to report it here - I glanced at someone else's issue, saw that it was mentioned that they may have an empty stat list, realized I hadn't created the (current) final character yet so I tried that as well, but no dice.  Attached is the zip folder with all the logs, as well as the JSON - which won't load into the companion either
[IdleonSaverBugReport.zip](https://github.com/desophos/idleon-saver/files/7757975/IdleonSaverBugReport.zip)

**Comment by desophos** [comment]
Thanks for the report. It's not quite the same error; your character bink_man appears to have no star signs equipped. Which star signs show as equipped in-game?

**Comment by mindofender** [comment]
There weren't any star signs equipped.  Interesting.  Equipped, trying again now

**Comment by mindofender** [comment]
That was it - after equipping star sign(s), It exported correctly
