### ISSUE TITLE
GUI can't find LegendsOfIdleon.exe

### ISSUE THREAD

**Issue by automorphis** [desophos/idleon-saver#3]
**Describe the problem**
the path selector couldn't find the LegendsOfIdleon.exe. I double checked that the path was correct

**Log**
[kivy_21-08-19_0.txt](https://github.com/desophos/idleon-saver/files/7018529/kivy_21-08-19_0.txt)
[kivy_21-08-19_1.txt](https://github.com/desophos/idleon-saver/files/7018530/kivy_21-08-19_1.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by desophos** [comment]
Thanks for the report! This should be fixed with fa563802e7a75730156ff75140e6ffa335c5579d.
