### ISSUE TITLE
KeyError on `xmasEvent3` card

### ISSUE THREAD

**Issue by rohitiyer11** [desophos/idleon-saver#30]
**Describe the problem**
When clicking export to idleon companion, i get an error that says Ooops something went wrong and to submit a bug report with the logs zip file and the idleon_save.json file attached. Won't let me attach json files so I made the save a .txt and attached it

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Start the Saver
2. Let it run then click export
3. See error

**Expected behavior**
To have the export json file saved properly for use w/ idleoncompanion.com/import

**Log file**
Please attach your log file, found at `%APPDATA%\IdleonSaver\idleon_saver.log`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Additional context**
[logs.zip](https://github.com/desophos/idleon-saver/files/7775501/logs.zip)
[idleon_save.txt](https://github.com/desophos/idleon-saver/files/7775502/idleon_save.txt)

**Comment by desophos** [comment]
You're getting an error on the `xmasEvent3` card. Please try [version 2.0.3](https://github.com/desophos/idleon-saver/releases/download/v2.0.3/IdleonSaver.exe), which fixes this issue.

**Comment by rohitiyer11** [comment]
Thx, working now :)
