### ISSUE TITLE
KeyError: "xmasEvent3"

### ISSUE THREAD

**Issue by vladburcea** [desophos/idleon-saver#33]
**Describe the problem**
When I try to export the data to Idleon Companion I get the error:
![image](https://user-images.githubusercontent.com/39880326/149426943-dff2b5c2-336f-4829-931a-40caed6d5c78.png)

If I try to manually upload it:
![image](https://user-images.githubusercontent.com/39880326/149427019-07eeceb2-473b-4bcc-ac35-5b1e7ec2fbb2.png)

I can't seem to make Idleon update the data, even though I tried all the listed methods:
- log in to all your characters
- open and close the game
- do things in-game like fighting monsters, changing presets, leveling up, etc.
- run Idleon Saver a couple times

**Desktop:**
 - OS: Windows 10

[LOGS](https://github.com/desophos/idleon-saver/files/7866687/logs.zip)

**Comment by desophos** [comment]
This error was fixed in v2.0.3. Please try the latest version: https://github.com/desophos/idleon-saver/releases/latest

**Comment by vladburcea** [comment]
That's the exact version I was running. Tried it again just now. Same results

**Comment by Reys813fan** [comment]
I'm also receiving this same issue on the current version.

**Comment by desophos** [comment]
My apologies, it looks like this error was re-introduced in v3.1.0. Please try [v3.1.1](https://github.com/desophos/idleon-saver/releases/latest), which should fix this issue.

**Comment by Reys813fan** [comment]
It is working for me now. Thank you for the quick fix!

**Comment by vladburcea** [comment]
Cheers! Works like a charm.
