### ISSUE TITLE
KeyError: "xmasEvent3"

### ISSUE THREAD

**Issue by HushK77** [desophos/idleon-saver#34]
Using 'IdleonSaver' to save Idleon data from Steam, attempts to upload to the Idleon Companion site fail and I'm given the response in the title. 

I have tried running IdleonSaver multiple times, have opened Idleon itself and played enough to try and force saves, run IdleonSaver repeatedly again, and am continuously getting that error response on the Idleon Companion site.

 - OS: WIndows 10

Log/Screenshot:

![scrnshot](https://user-images.githubusercontent.com/97865024/149705513-dc8a52a6-1bf8-4844-9c5d-461cb945f082.jpg)
[logs.zip](https://github.com/desophos/idleon-saver/files/7878856/logs.zip)

won't allow me to attach idleon_save.json (for some reason it says it's not a supported file type)

Thanks for any help!! :)

**Comment by desophos** [comment]
Please try [version 3.1.1](https://github.com/desophos/idleon-saver/releases/latest), which fixes this issue.

**Comment by desophos** [comment]
Closing as fixed, please reopen if this error still occurs.
