### ISSUE TITLE
idleon_companion.json normal storage chests used doesn't import

### ISSUE THREAD

**Issue by Chewypuppielover** [desophos/idleon-saver#36]
**Describe the problem**

**Expected behavior**
when I import to idleon companion the storage chests (1-13,15-21, dank) should be shown as used

**Log file**
Please attach your log file, found at `%APPDATA%\IdleonSaver\idleon_saver.log`.
[log_22-01-28_4.txt](https://github.com/desophos/idleon-saver/files/7961321/log_22-01-28_4.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
In my save file I have
`"InvStorageUsed": {
   "0": "3",
   "1": "3",
   "2": "3",
   "3": "3",
   "4": "3",
   "5": "4",
   "6": "4",
   "7": "4",
   "8": "4",
   "9": "5",
   "10": "5",
   "11": "5",
   "12": "5",
   "13": "6",
   "15": "6",
   "16": "6",
   "17": "6",
   "18": "6",
   "19": "7",
   "20": "7",
   "30": "6",
   "31": "6",
   "32": "6",
   "33": "6",
   "34": "6",
   "35": "6",
   "36": "6",
   "37": "6",
   "100": "3"
},`
but in the companion json I only have this in the checklist chest section:
`     "Storage Chest 90": true,
      "Storage Chest 91": true,
      "Storage Chest 92": true,
      "Storage Chest 93": true,
      "Storage Chest 94": true,
      "Storage Chest 95": true,
      "Storage Chest 96": true,
      "Storage Chest 97": true,`
I'm guessing it's a problem with the wiki_data, the key pair I have observed is:
`  "0": "3"= Storage Chest 1,
   "1": "3"= Storage Chest 2,
   "2": "3"= Storage Chest 3,
   "3": "3"= Storage Chest 4,
   "4": "3"= Storage Chest 5,
   "5": "4"= Storage Chest 6,
   "6": "4"= Storage Chest 7,
   "7": "4"= Storage Chest 8,
   "8": "4"= Storage Chest 9,
   "9": "5"= Storage Chest 10,
   "10": "5"= Storage Chest 11,
   "11": "5"= Storage Chest 12,
   "12": "5"= Storage Chest 13,
   "13": "6"= Storage Chest 15,
   "15": "6"= Storage Chest 16,
   "16": "6"= Storage Chest 17,
   "17": "6"= Storage Chest 18,
   "18": "6"= Storage Chest 19,
   "19": "7"= Storage Chest 20,
   "20": "7"= Storage Chest 21,
   "30": "6"= Storage Chest 90,
   "31": "6"= Storage Chest 91,
   "32": "6"= Storage Chest 92,
   "33": "6"= Storage Chest 93,
   "34": "6"= Storage Chest 94,
   "35": "6"= Storage Chest 95,
   "36": "6"= Storage Chest 96,
   "37": "6"= Storage Chest 97,
   "100": "3"= Dank Paypay Chest`

**Comment by desophos** [comment]
Thanks, this was actually a bug in my logic that has been present for a while!
