### ISSUE TITLE
FirebaseError: No Firebase App has been created

### ISSUE THREAD

**Issue by jaamulberry** [desophos/idleon-saver#38]
**Describe the problem**
Clicking on Export causes error

**Log files**
[logs.zip](https://github.com/desophos/idleon-saver/files/8124747/logs.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/25511935/155332158-16af7102-c778-4868-b59d-96e2d3246d69.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Game and program are installed on D drive. Made sure both were on the same drive per instructions. Tried running as administrator and got same error.

**Comment by desophos** [comment]
Hmm, your logs show that Firebase isn't initialized for some reason. Have you tried launching the game normally, logging in to a character, closing the game, then running Idleon Saver?

**Comment by jaamulberry** [comment]
It is working now but I can't find a rhyme or reason to why it doesn't. Log shows the same error but I did get it working yesterday after awhile. I'll close this issue since it's working now.
