### ISSUE TITLE
KeyError: 'w4b4' card

### ISSUE THREAD

**Issue by oddmonstr** [desophos/idleon-saver#41]
[logs.zip](https://github.com/desophos/idleon-saver/files/8247560/logs.zip)
**Describe the problem**
error when exporting for idleon companion

**Log files**
Please attach your logs.zip file, found at `%APPDATA%\IdleonSaver\logs.zip`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] windows 10

**Additional context**

**Comment by desophos** [comment]
Please try [the latest release](https://github.com/desophos/idleon-saver/releases/latest); this should be fixed in v3.1.4.

**Comment by oddmonstr** [comment]
Fixed! thank you!
