### ISSUE TITLE
KeyError: 'mushP' card

### ISSUE THREAD

**Issue by Axis38** [desophos/idleon-saver#42]
**Describe the problem**
The app doesn't let me export to idleon companion and when i try manually uploading it, it says it's not formated correctly or is outdated.

**Log files**
[logs.zip](https://github.com/desophos/idleon-saver/files/8255185/logs.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/101657576/158422417-96d8c85a-d58c-4719-8b2a-faf5de243061.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by desophos** [comment]
Please try [the latest release](https://github.com/desophos/idleon-saver/releases/latest); this should be fixed in v3.1.4.

**Comment by Axis38** [comment]
Works now. Thanks for the fix
