### ISSUE TITLE
KeyError: 'w4c2' card

### ISSUE THREAD

**Issue by JordanRheeder** [desophos/idleon-saver#43]
**Describe the problem**
Initial export is fine, however, the export for IdleOn Companion results in error.

**Log files**
Please attach your logs.zip file, found at `%APPDATA%\IdleonSaver\logs.zip`.
[logs.zip](https://github.com/desophos/idleon-saver/files/8308945/logs.zip)

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by desophos** [comment]
Please try [the latest release](https://github.com/desophos/idleon-saver/releases/latest); this should be fixed in v3.1.4.

**Comment by JordanRheeder** [comment]
Resolved, Thank you! :)
