### ISSUE TITLE
KeyError: 'demonP' card

### ISSUE THREAD

**Issue by zaphida** [desophos/idleon-saver#44]
**Describe the problem**
I hit Export to Idleon Companion several times and I keep getting Oops! Something went wrong.

**Log files**
Please attach your logs.zip file, found at `%APPDATA%\IdleonSaver\logs.zip`.
[logs.zip](https://github.com/desophos/idleon-saver/files/8309115/logs.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/12946330/159119756-0e25a547-4adf-48d4-a9af-32e6d8820014.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
Windows 10 Pro 21H2

**Additional context**
I don't have a cat at home :(

**Comment by zaphida** [comment]
KeyError: 'demonP' card?

**Comment by desophos** [comment]
Yes, that's the error in your logs. This is happening because the data hasn't been updated for Idleon 1.5 yet. I'm working on a fix.

**Comment by zaphida** [comment]
Oh ok, well good luck! Thanks for making this tool!

**Comment by desophos** [comment]
Thanks, I appreciate it. Please try [the latest release](https://github.com/desophos/idleon-saver/releases/latest); this should be fixed in v3.1.4.

**Comment by zaphida** [comment]
The latest release works :)
